export {default as standard} from "./Standard";
export {default as name} from "./Name";
export {default as select} from "./Select";
export {default as educationLevel} from "./RelationName";
export {default as options} from "./Options";
export {default as field} from "./Field";
export {default as orderedRelations} from "./OrderedRelations";
export {default as relations} from "./Relations";
export {default as relationOfAnyType} from "./RelationOfAnyType";